ainit pass for wso2

diff --git a/infrastructure/docker-compose.yml b/infrastructure/docker-compose.yml
--- a/infrastructure/docker-compose.yml
+++ b/infrastructure/docker-compose.yml
@@ -313,9 +313,12 @@ services:
     networks:
       - obi_net
     environment:
+      - POSTGRES_ENV_POSTGRES_PASSWORD={--postgres_password--}    
       - WSO2_DB_USER=wso2dbuser
       - WSO2_DB_PASS={--wso2_db_pass--}
       - WSO2_DB_NAME=wso2db
+      - WSO2_DB_HOST=postgres
+      - WSO2_INIT_PASS={--wso2_admin_init_pass--}
     ports:
       - 9443:9443
       - 9763:9763
@@ -323,8 +326,9 @@ services:
     volumes:
       - ${PWD}/assets/wso2carbon/wso2is-5.5.0/repository/conf/carbon.xml:/home/wso2carbon/wso2is-5.5.0/repository/conf/carbon.xml
       - ${PWD}/assets/wso2carbon/wso2is-5.5.0/repository/components/dropins/org.wso2.carbon.identity.application.authenticator.government.gsis-5.1.3.jar:/home/wso2carbon/wso2is-5.5.0/repository/components/dropins/org.wso2.carbon.identity.application.authenticator.government.gsis-5.1.3.jar
-      - ${PWD}/assets/wso2carbon/wso2is-5.5.0/repository/components/lib/postgresql-42.2.2.jar:/home/wso2carbon/wso2is-5.5.0/repository/components/lib/postgresql-42.2.2.jar
       - ${PWD}/assets/wso2carbon/wso2is-5.5.0/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/master-datasources.xml
+      - ${PWD}/assets/wso2carbon/wso2is-5.5.0/repository/conf/user-mgt.xml:/home/wso2carbon/user-mgt.xml
+      - ${PWD}/assets/wso2carbon/wso2is-5.5.0/repository/resources/security/wso2carbon.jks:/home/wso2carbon//wso2is-5.5.0/repository/resources/security/wso2carbon.jks
     deploy:
       replicas: 0
       restart_policy:
@@ -337,9 +341,23 @@ services:
       - -c
       - |
         set -e
+        echo 'Waiting for Postgres to be available'
+        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
+        maxTries=20
+        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$WSO2_DB_HOST" -U 'postgres' -c '\l'; do
+            let maxTries--
+            sleep 5
+        done
+        echo
+        if [ "$$maxTries" -le 0 ]; then
+            echo >&2 'error: unable to contact Postgres after 20 tries'
+            exit 1
+        fi        
         #you cant change inode of mounted by docker file so copy it in place and then sed
         cp /home/wso2carbon/master-datasources.xml /home/wso2carbon/wso2is-5.5.0/repository/conf/datasources/master-datasources.xml
         sed -i "s/{--wso2_db_pass_replace--}/$${WSO2_DB_PASS}/g" /home/wso2carbon/wso2is-5.5.0/repository/conf/datasources/master-datasources.xml
+        cp /home/wso2carbon/user-mgt.xml /home/wso2carbon/wso2is-5.5.0/repository/conf/user-mgt.xml
+        sed -i "s/{--wso2_admin_init_pass_replace--}/$${WSO2_INIT_PASS}/g" /home/wso2carbon/wso2is-5.5.0/repository/conf/user-mgt.xml        
         exec /home/wso2carbon/start.sh        
         
 
